#!/bin/sh

# Define staged files (ready for commit)
# .husky/pre-commit
stagedFiles=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')

# Define changed files (not necessarily staged)
changedFiles=$(git diff --name-only --diff-filter=ACMR | sed 's| |\\ |g')

# Function to apply Prettier and ESLint on files
run_tools() {
  files=$1
  if [ -n "$files" ]; then
    echo "🔍 Applying FSLint..."
    npx tsx ./scripts/fs-lint/index.ts --fix
    echo "\n"

    echo "🛠️ Applying Prettier..."
    prettier $files --write --ignore-unknown
    echo "\n"

    echo "🔍 Applying ESLint..."
    eslint $files --fix
    echo "\n"

    echo "✔ Updating Git indexes..."
    git update-index --again
    echo "\n"

    # Checks the test status
    if [ $? -ne 0 ]; then
      echo "✘ Tests failed. Aborting commit."
      exit 1
    fi
  else
    echo "⚠️ No files found to process."
  fi
}

# echo "🔄 Processing all modified files..."
# run_tools "$changedFiles"

echo "🔄 Processing staged files..."
run_tools "$stagedFiles"
